services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped      #no always on-failure unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dados:/data
    command: redis-server --appendonly yes


volumes:
  redis_dados:
    driver: local
