name: Deploy VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /root/app/usuario
            git pull origin master
            cd ..
            docker compose down --remove-orphans
            docker compose build --no-cache usuario
            docker compose up -d --force-recreate usuario
